### ISSUE TITLE
hbc using cuHE

### ISSUE THREAD

**Issue by SayyedF** [qdm12/hbc#2]
Hi Quentin,

Sorry to ask here!!!
Can I write hbc over cuHE (for my masters project)? and which statistical operations are supported by hbc??

**Comment by qdm12** [comment]
Hi there !

I would recommend you to quickly go through this [presentation](https://www.dropbox.com/s/scrwpum0avtqxuw/Presentation.pptx?dl=1). It is only a few slides that everyone in computer science could easily understand (I hope).  To sum up, I have used HElib to build XOR, AND and NOT gates and then built all more complex circuits like Multiplication from them. Now, multiplication works for example until 8 bits and then takes way too much time/resources. To use CuHE, you'd have to adapt my code to use cuHE instead of HElib which is not easy but feasible. It it is mostly about finding a way to implement the basic logic gates with CuHE. Let me know if you have any other questions!

Good luck!

**Comment by SayyedF** [comment]
Okay.
Thank you for getting back to me!!!
